# Generated by Django 2.0.3 on 2018-05-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaDia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='total',
        ),
        migrations.AlterField(
            model_name='venta',
            name='cantidad',
            field=models.IntegerField(verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio',
            field=models.IntegerField(verbose_name='precio'),
        ),
    ]
