# Generated by Django 2.0.3 on 2018-05-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaDia', '0002_auto_20180529_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
