# Generated by Django 2.0.3 on 2018-05-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaDia', '0003_auto_20180529_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
